---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: rag-chatbot-test-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rag-chatbot-test-app 
  name: rag-chatbot-test-app
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi