apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rag-chatbot-test-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rag-chatbot-test-app 
  name: rag-chatbot-test-app
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: rag-chatbot-test-app 
